name: py-starter
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.10.15
  - certifi=2018.10.15
  - docutils=0.14
  - freetype=2.6.3
  - gettext=0.19.8.1
  - glib=2.56.2
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - jpeg=9c
  - kivy=1.10.1
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.35
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - libxcb=1.13
  - ncurses=6.1
  - olefile=0.46
  - openssl=1.0.2p
  - pcre=8.41
  - pillow=4.0.0
  - pip=18.1
  - pthread-stubs=0.4
  - pygments=2.2.0
  - python=3.6.6
  - readline=7.0
  - sdl2=2.0.8
  - sdl2_image=2.0.2
  - sdl2_mixer=2.0.1
  - sdl2_ttf=2.0.14
  - setuptools=40.5.0
  - smpeg2=2.0.0
  - sqlite=3.25.2
  - tk=8.6.8
  - wheel=0.32.2
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - zlib=1.2.11

